# Lab Session 2: Numpy
Hermina Petric Maretic, *PhD student*, [EPFL](http://epfl.ch) [LTS4](http://lts4.epfl.ch)

[NumPy](http://www.numpy.org) is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np

In [2]:
#create a numpy array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
#or a 2 dimensional array
m = np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [4]:
m[0,0]

1

In [5]:
m[:,1]

array([2, 4])

In [6]:
a[:2]

array([1, 2])

In [7]:
a[-2] #second last element of the array

3

In [8]:
a[-2:] #last two elements of the array

array([3, 4])

### Careful if you're used to Python list

In [9]:
b = [1,2,3,4]

In [11]:
b + b


[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
a + a


array([2, 4, 6, 8])

In [14]:
#if you want to add elements to a
np.append(a,a)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [15]:
np.append(a,[1,2,3])

array([1, 2, 3, 4, 1, 2, 3])

In [16]:
np.insert(a, 1, 5) #insert 5 on position number 1

array([1, 5, 2, 3, 4])

### Basic arithmetics with numpy arrays

In [17]:
a + 3

array([4, 5, 6, 7])

In [18]:
a * 3

array([ 3,  6,  9, 12])

In [19]:
a ** 3

array([ 1,  8, 27, 64])

In [20]:
a * a

array([ 1,  4,  9, 16])

In [21]:
a.sum()

10

In [22]:
m * m #still elementwise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [23]:
np.dot(m,m) #standard matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [24]:
m = np.matrix(m) #there is a type matrix
m * m #for matrices, multiplication works as we're used to

matrix([[ 7, 10],
        [15, 22]])

### Some functions to create arrays

In [25]:
x = np.arange(0,10,2) #beginning, end, step
x

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,10,10) #beginning, end, number of variables

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [29]:
np.logspace(0,10,10,base=2) #beginning, end, number of variables

array([  1.00000000e+00,   2.16011948e+00,   4.66611616e+00,
         1.00793684e+01,   2.17726400e+01,   4.70315038e+01,
         1.01593667e+02,   2.19454460e+02,   4.74047853e+02,
         1.02400000e+03])

In [30]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [32]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [33]:
np.random.rand(5,2)

array([[ 0.69264681,  0.17550431],
       [ 0.49450672,  0.9465809 ],
       [ 0.6052853 ,  0.32028344],
       [ 0.88699052,  0.3744377 ],
       [ 0.11524805,  0.80376991]])

### Some linear algebra functions

In [34]:
np.diag(m)

array([1, 4])

In [35]:
np.trace(m)

5

In [36]:
m.T

matrix([[1, 3],
        [2, 4]])

In [37]:
m1 = np.linalg.inv(m)
m1

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [38]:
np.linalg.det(m)

-2.0000000000000004

In [39]:
np.linalg.det(m1)

-0.50000000000000011

In [40]:
[eival, eivec] = np.linalg.eig(m)

In [41]:
eival

array([-0.37228132,  5.37228132])

In [42]:
eivec

matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]])

In [44]:
x= np.random.rand(10,50)
x

array([[ 0.70690769,  0.87174352,  0.74294744,  0.32653873,  0.68009762,
         0.1470322 ,  0.0223547 ,  0.51252694,  0.88278452,  0.80080283,
         0.20471094,  0.41037036,  0.80218855,  0.50609837,  0.05909689,
         0.54238232,  0.00424131,  0.16352804,  0.98483386,  0.38433303,
         0.64113957,  0.78447256,  0.40947648,  0.82965555,  0.42005641,
         0.57799219,  0.49622592,  0.0484381 ,  0.75427031,  0.39175014,
         0.42071189,  0.36350871,  0.90441693,  0.79122642,  0.57840094,
         0.66418711,  0.06171153,  0.63392399,  0.08820408,  0.35377163,
         0.69717974,  0.62888098,  0.85114108,  0.8865983 ,  0.60546021,
         0.58707732,  0.03423213,  0.03205447,  0.02148668,  0.40841778],
       [ 0.88106537,  0.70803588,  0.0053766 ,  0.25433748,  0.1159593 ,
         0.81342927,  0.64656282,  0.03611832,  0.65779037,  0.29280131,
         0.7973056 ,  0.567041  ,  0.51371253,  0.25437605,  0.45425806,
         0.27373894,  0.34992437,  0.50313964,  0.

In [45]:
 c = np.dot(x.T,x)

In [46]:
c

array([[ 6.21797091,  3.67527493,  3.07560089, ...,  3.60230974,
         3.55983451,  3.91116274],
       [ 3.67527493,  3.00529374,  1.97423284, ...,  1.75413512,
         1.78453749,  2.35789541],
       [ 3.07560089,  1.97423284,  2.62996244, ...,  1.3663835 ,
         1.71213315,  2.14337136],
       ..., 
       [ 3.60230974,  1.75413512,  1.3663835 , ...,  3.15336878,
         2.52792208,  1.86904939],
       [ 3.55983451,  1.78453749,  1.71213315, ...,  2.52792208,
         2.65526339,  2.1036477 ],
       [ 3.91116274,  2.35789541,  2.14337136, ...,  1.86904939,
         2.1036477 ,  2.89937059]])

In [47]:
np.linalg.det(c)

0.0